### ISSUE TITLE
dcd-server not detected in OS X

### ISSUE THREAD

**Issue by dzaragoza** [LaurentTreguier/autocomplete-dcd#1]
Hi

I get this error when using this package in atom:

'dcd-server' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

I checked:
- dcd-server is on PATH: Message appears.
- Manually started dcd-server: Message appears.

What could be missing? 

Regards

**Comment by LaurentTreguier** [comment]
I don't know much about Mac OS X and just hoped it would work just like on linux... I created a branch named `bug-1` which logs the actual error in Atom's console. Could you switch branches in your local Atom package directory or replace `autocomplete-dcd/lib/dcd-provider.coffee` with the one from the `bug-1` branch ? Then perhaps there will be a more helpful error message logged in Atom's console.

EDIT : does the error happen when you enable the package ? Or only when opening a second Atom window for example ?

**Comment by dzaragoza** [comment]
I found the problem. Atom in OS X has problems with PATH in applications launched from the GUI. Launching atom from the terminal solves the problem. See https://github.com/atom-community/linter/issues/150 for more details.

autocomplete-dcd works without problem.

**Comment by LaurentTreguier** [comment]
@dzaragoza Have you seen the [environment](https://atom.io/packages/environment) package ? It looks like it could fix this problem with OS X.
