### ISSUE TITLE
include binaries

### ISSUE THREAD

**Issue by gedaiu** [LaurentTreguier/autocomplete-dcd#7]
Hi,

It would be awesome if the DCD binaries would be included in this plugin...

Thanks!

**Comment by LaurentTreguier** [comment]
Including binaries in plugins is not a really good idea in my opinion. They should be installed outside of plugins to allow for easier upgrade and maintaining, as well as not having to update the extension solely for updating the binaries.

Which OS are you using ?

**Comment by gedaiu** [comment]
Linux and MacOS... the reason why  I am asking for this is because there are a couple of newbies with Dlang that I know that they will not use this plugin because it requires some setup...

**Comment by LaurentTreguier** [comment]
I see... Maybe I can try to do what I did with [this VSCode plugin](https://github.com/dlang-vscode/dlang-vscode), and use dub within the extension to automatically download and build DCD. I don't use Atom anymore so I didn't plan on updating this extension much, but I'll see what I can do.

**Comment by gedaiu** [comment]
it would be awesome!

thanks!

**Comment by LaurentTreguier** [comment]
Also, which Linux distribution are being used here ? On Ubuntu DCD can be installed from the [D Apt repository](http://d-apt.sourceforge.net/) (that is probably where most people get DMD already), and on MacOS there is a Homebrew formula.

**Comment by gedaiu** [comment]
I'm using fedora. I compiled DCD from source. I'm worried about the less experienced users...

**Comment by LaurentTreguier** [comment]
I'm sorry for the delay, I kind of forgot about this and I'm getting into it again.
I have a question though : are the other users you are talking about also using Fedora ? As I am using it myself, I have made some dmd and dub packages for Fedora. Making a DCD package would be easy and would make for a quick workaround while the extension is getting fixed.

**Comment by LaurentTreguier** [comment]
It should now automatically install DCD after the new update with dub. I don't plan on adding features since I don't use Atom anymore, but don't hesitate to notify me about bugs !

**Comment by gedaiu** [comment]
awesome! thanks!
